### ISSUE TITLE
Chapter 19.2 on MGFs in Bernoulli

### ISSUE THREAD

**Issue by alexnakagawa** [data-140-berkeley/textbook#6]
Hi! I noticed that in public github pages website, there's a part where it claims that the MGF for the Bernoulli is $$1−p(e^t−1)$$, when it should be $$1+p(e^t−1)$$. I checked your content folder for the `02_Moment_Generating_Functions.ipynb` notebook, and noticed that the error is already resolved there within the notebook, so I think it's just a matter of recompiling that chapter in particular.

https://textbook.prob140.org/notebooks-md/19_02_Moment_Generating_Functions.html

**Comment by choldgraf** [comment]
thanks for letting us know! it looks like the book needs an upgrade in order for the build / deploy to work, I'll try and fix this soon

**Comment by shahzarrizvi** [comment]
Fixed.
